### ISSUE TITLE
qt5: several SQL errors + rdadmin coredump

### ISSUE THREAD

**Issue by kernelpanic3** [ElvishArtisan/rivendell#673]
Hi there,

While setting up a qt5/4.0 testbed, I ran into a whole host of issues that prevented me from progressing further - mostly SQL errors.

First off, when attempting to add a new user:
``invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('')' at line 1 QMYSQL: Unable to execute query]: insert into `USERS` set `LOGIN_NAME`='sunshine',`PASSWORD`=PASSWORD('')``

Then, when editing a clock:
``invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''SunshineGenerici' at line 1 QMYSQL: Unable to execute query]: select `SHORT_NAME`,`COLOR`,`ARTISTSEP`,`REMARKS` from `CLOCKS` where `NAME`='SunshineGenerici``

Editing events:
``invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUPS order by NAME' at line 1 QMYSQL: Unable to execute query]: select NAME from GROUPS order by NAME``

And finally, when editing scheduler codes, a Qt-related bug that crashes RDAdmin:
``ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 544
Aborted (core dumped)``

The setup is a fresh install of Ubuntu 20.04, MySQL 8.0.25, and RD compiled from the latest qt5 branch source.

Thanks a lot in advance. Feeling very glad I did this testing first ... my main 3.x setup is still chugging away like clockwork.

**Comment by ElvishArtisan** [comment]
> First off, when attempting to add a new user:
invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('')' at line 1 QMYSQL: Unable to execute query]: insert into `USERS` set `LOGIN_NAME`='sunshine',`PASSWORD`=PASSWORD('')

Fixed in f7ade0d.

**Comment by ElvishArtisan** [comment]
> Editing events:
invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUPS order by NAME' at line 1 QMYSQL: Unable to execute query]: select NAME from GROUPS order by NAME

Fixed in 30e643e.

**Comment by kernelpanic3** [comment]
> > And finally, when editing scheduler codes, a Qt-related bug that crashes RDAdmin:
> > ASSERT failure in QList::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 544 Aborted (core dumped)
> 
> This one I was not able to reproduce; how exactly did you goose it?

It was a bit inconsistent (and I unfortunately can't test further with the same setup at the moment), but generally attempting to add or edit a code would trigger the crash as soon as the "OK" button was pressed. The code was still added/edited correctly, though.

I'll retest this weekend and see if I can still reproduce it with another fresh compile.

**Comment by kernelpanic3** [comment]
> > The setup is a fresh install of Ubuntu 20.04, MySQL 8.0.25, and RD compiled from the latest qt5 branch source.
> 
> Thank you for the report; this is _exactly_ the kind of feedback I'm looking for right now.
> 
> > Thanks a lot in advance. Feeling very glad I did this testing first ... my main 3.x setup is still chugging away like clockwork.
> 
> Yup. We still have a bit of a journey ahead of us before 4.x is ready for prime time.

Glad I can be of some help! I'll be sure to keep poking at it with a stick when I have some chances to do so.

**Comment by ElvishArtisan** [comment]
> It was a bit inconsistent (and I unfortunately can't test further with the same setup at the moment), but generally attempting to add or edit a code would trigger the crash as soon as the "OK" button was pressed. The code was still added/edited correctly, though.

So this was in RDAdmin->Scheduler Codes then?

**Comment by kernelpanic3** [comment]
> > It was a bit inconsistent (and I unfortunately can't test further with the same setup at the moment), but generally attempting to add or edit a code would trigger the crash as soon as the "OK" button was pressed. The code was still added/edited correctly, though.
> 
> So this was in RDAdmin->Scheduler Codes then?

Yes - sorry if I didn't make that entirely clear.

**Comment by ElvishArtisan** [comment]
I've still not been able to reproduce this here. It's possible that one of the fixes above also corrected this.

If you have not seen this since then, I'd like to close this issue, with the understanding that it can be reopened in the event the problem recurs.

**Comment by kernelpanic3** [comment]
> I've still not been able to reproduce this here. It's possible that one of the fixes above also corrected this.
> 
> If you have not seen this since then, I'd like to close this issue, with the understanding that it can be reopened in the event the problem recurs.

Very sorry for the radio silence ... other work came up and I've not yet had the chance to properly retest on my own end. No objections on this end to doing that until/unless I can reproduce.

**Comment by ElvishArtisan** [comment]
Ok.
